//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Builder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int ID { get; set; }
        public string message { get; set; }
        public Nullable<int> gradeValue { get; set; }
        public Nullable<int> adminAccept { get; set; }
        public int reservation_id { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
