//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Builder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Opinions = new HashSet<Opinion>();
            this.ReservationTerms = new HashSet<ReservationTerm>();
        }
    
        public int ID { get; set; }
        public int company_id { get; set; }
        public int customer_id { get; set; }
        public string approval { get; set; }
        public Nullable<System.DateTime> firstConversDate { get; set; }
        public Nullable<System.DateTime> confimDate { get; set; }
        public string description { get; set; }
        public string companyReplay { get; set; }
        public string status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationTerm> ReservationTerms { get; set; }
    }
}
