//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Builder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationTerm
    {
        public int ID { get; set; }
        public Nullable<int> term_id { get; set; }
        public Nullable<int> reservation_id { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Term Term { get; set; }
    }
}
